---
name: main
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7  # v5.0.2
        with:
          path: '/home/runner/work/codemirror/codemirror5/node_modules'
          key: ${{ runner.os }}-modules

      - run: npm install

      - run: npm test
